import type { NextPage } from 'next'
import Head from 'next/head'
import { Form } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SWR demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello SWR!!</h1>
        <Form />
      </main>
    </div>
  )
}

export default Home
